apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-cloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/arucard21/personal-cloud.git
    path: personal-cloud
    targetRevision: eb4c0411e39444510ef670f5c37e04f2996338e6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
