apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 6.5.1
    helm:
      valuesObject:
        nextcloud:
          host: {{ .Values.cluster.hostname.nextcloud }}
          trustedDomains:
            - {{ .Values.cluster.hostname.nextcloud }}
        ingress:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
