gitea:
  redis-cluster:
    enabled: false
  redis:
    enabled: true
  postgresql:
    enabled: true
  postgresql-ha:
    enabled: false
  persistence:
    enabled: true
  ingress:
    enabled: true
    hosts:
      - host: git.personal.cloud
        paths:
          - path: /
            pathType: Prefix
  gitea:
    config:
      database:
        DB_TYPE: postgres
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
    admin:
      username: "cloudadmin"
      password: "personalcloudadmin"
      email: "admin@personal.cloud"
