apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: argocd-route
spec:
  http:
    - name: argocd-route-match
      match:
        hosts:
          - argocd.personal.cloud
        paths:
          - /*
      backends:
        - serviceName: argocd-server
          servicePort: 443
