apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apisix
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/arucard21/personal-cloud.git
    path: apisix
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - .spec.versions.[].additionalPrinterColumns.[].priority
