apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-cloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://cloudadmin:personalcloudadmin@gitea-http.git:3000/cloudadmin/gitops-charts.git
    path: personal-cloud
    targetRevision: HEAD
    helm:
      valuesObject:
        cluster:
          hostname:
            nextcloud: nextcloud.personal.cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
