apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/arucard21/personal-cloud.git
    path: chart/argo-cd
    targetRevision: HEAD
    helm:
      valuesObject:
        argo-cd:
          global:
            domain: {{ .Values.cluster.hostname.argocd }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
