apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    path: gateway
    targetRevision: 1.24.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
