apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/arucard21/personal-cloud.git
    path: chart/istio-gateway
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
