apisix:
  dashboard:
    enabled: true
  ingress-controller:
    enabled: true
    config:
      kubernetes:
        enableGatewayAPI: true
      apisix:
        serviceNamespace: apisix
  apisix:
    deployment:
      mode: standalone
      role: data_plane
  etcd:
    enabled: false
