apisix:
  dashboard:
    enabled: true
  ingress-controller:
    enabled: true
    gateway:
      type: LoadBalancer
      externalTrafficPolicy: Local
    config:
      kubernetes:
        enableGatewayAPI: true
      apisix:
        serviceNamespace: apisix
      ingressPublishService: apisix/apisix-gateway
