apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: nextcloud-route
spec:
  http:
    - name: nextcloud-http-rule
      match:
        hosts:
          - nextcloud.personal.cloud
      backends:
        - serviceName: nextcloud
          servicePort: 80
