apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: nextcloud-route
spec:
  http:
    - name: nextcloud-route-match
      match:
        hosts:
          - nextcloud.personal.cloud
        paths:
          - /*
      backends:
        - serviceName: nextcloud
          servicePort: 80
