apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: nextcloud-route
spec:
  http:
    - name: nextcloud-http-rule
      match:
        # hosts:
        #   - nextcloud.personal.cloud
        paths:
          - /*
      backends:
        - serviceName: nextcloud
          servicePort: 8080
          resolveGranularity: service
